### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by leowald** [leowald/yeshtikvah#13]
- [ ] Under the pages directory create components for each menu item (for now it should return an empty div)

Stories - only create one.

Home
About
Subscribe
Donate
Contact
Account
Sources
Pesukim
FAQ
Shiurim

**Comment by leowald** [comment]
I don't see the branch you created with these changes.
You need to create a new branch and then make changes and then push them up.
Did you see the video of the meeting you missed. You should follow what to do there.
This task is just an easy task to get you used to the whole branch / pull request.

**Comment by CLobenstein** [comment]
I thought I was supposed to add the pages on wordpress...
I did it there...

**Comment by CLobenstein** [comment]
Because I didn't see a 'pages directory' anywhere in our react project...

**Comment by leowald** [comment]
Sorry, you should create the pages directory and then create them under it.
