### ISSUE TITLE
Alert Component

### ISSUE THREAD

**Issue by leowald** [leowald/yeshtikvah#30]
Use Bootstrap alert to create a component which will create an alert box. Here are examples of a bootstrap alert box
![image](https://github.com/user-attachments/assets/cee4e1ed-c1c3-42d8-aad9-dab2bd9b7a72)

- [x] Create the component. It should be a wrapper component that accepts children and the type of alert box. Based on the "type" passed in via props, the colors of the box will differ. The component should create any type of bootstrap alerts: ie: primary,secondary,success and so on..

- [x] Create it such that when a user clicks on the X the box disappears.
- [x] Add an additional props called flex. The default for this should be false such that if this is not passed in via props it is automatically false. (look up how to add defaults to props). If this property is true, items passed in via children are flexed. If false they are not.
The following diagram illustrates the difference.
Flex=true 
If the following children are passed:
`  <h1>Test to see what this looks like</h1>
      <p>test to see what info this looks like</p>`
![image](https://github.com/user-attachments/assets/bae6f05f-1554-4637-ade5-7ded0566fcb0)

With the same children but flex = false (the default)

![image](https://github.com/user-attachments/assets/d56d792a-c48d-4a78-a0a9-60c4038633d6)

- [x] Write unit tests for this component
- [x] Write documentation for this component.

**Comment by zippy1043** [comment]
A few points:
1)  When flexing the Alert box, I can't get the padding around the children as you have in your example above.  The only way I can see it can be done is if the Bootstrap classes is passed in together with the text. 
2)  I have limited the {type} prop to the 8 different Alert box styles for validation.  But the disadvantage is that if Bootstrap adds a new style then the code would have to be adjusted.
3) I'm not sure what the correct PropType for the children is.  I did it: 
 oneOfType([PropTypes.string, PropTypes.element]).
