### ISSUE TITLE
React Router

### ISSUE THREAD

**Issue by leowald** [leowald/yeshtikvah#46]
Even though React apps are one page applications we want to be able to navigate its pages just like we would a regular website. For example we want to be able to go to http//yeshtivkah.com/contact and get to the contact page or yeshtikvah.com/stories and get to the stories page. To do this we are going to use React Router.

- [x] Install [React Router Dom](https://www.npmjs.com/package/react-router-dom)
- [x] Create routes for the following pages: By creating routes I mean that when you go to 

- http://localhost:5173/about you will see the about page (located in pages)
- http://localhost:5173/contact you will see the contact page
- http://localhost:5173/donate you will see the donate page
- http://localhost:5173/faq you will see the faq page
- http://localhost:5173/ will load App
- http://localhost:5173/pesukim will see the pesukim page
- http://localhost:5173/shiurim will see the shiurim page
- http://localhost:5173/sources will see the sources page
- http://localhost:5173/stories will see the stories page
- http://localhost:5173/subscribe will see the subscribe page

We should be able to add on a parameter to the stories such that 
http://localhost:5173/stories/shidduchim will bring us to a page that will have all the shidduchim related categories
http://localhost:5173/stories/parnassah will bring to a page that will have all parnassah related categories.
These routes should not be hardcoded but anything passed to /stories/x should be valid.

There are two ways to define routes, jsx and regular javascript object. Use the jsx method (the sample tutorial I put below uses  jsx also)

- [x] Change pages/stories so that title reflects whatever was passed in the url so the heading of http://localhost:5173/stories/shidduchim should display  <h1>shidduchim </h1>

To use React Router[ I found this tutorial helpful](https://medium.com/@navanitvishwakarma790/mastering-react-router-dom-with-vite-an-optimized-guide-08e870cce6e2). [The official react router tutorial ](The official react router tutorial )is also good, but has probably more than you need - the part to focus here is on JSX routes and parameters. Free free to use any tutorial you find but make sure it is current as there are older versions of React Router. 

- [x] Add unit tests for the routes. We want to test that are routes are set up properly so for each route we need a separate test to verify if we go to that route, we see the right content. (For now add H1 to all pages so you can have something to verify what page we are on - will have the change the test later to reflect real data). What is important here is that where you used createBrowserRouter in the main application, it won't work in our tests as it only works in a browser. Instead you can make use of the CreateMemoryRouter function and pass in the path you want to go to as initalEntries so const router = createMemoryRouter(routes, { initialEntries: ["/"] }); - would simulate going to the root path /

Use the same routes in the test that you are using on the main site (read them in from the same file). To do this you need to move them to their own file (routes.jsx) and save to a variable and export it.

**Comment by zippy1043** [comment]
I didn't change the links in App.jsx to use the React Router Link since it wasn't on the task list.  Did you want me to do that?

Also - for the tests - I created a new MemoryRouter for each test.  It seemed repetitive but I couldn't see how to do it otherwise.  Is there a more concise way?
